version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached
    
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGHOST: postgres
      POSTGRES_DB: postgres

      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:postgres

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  postgres:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  hbase:
    image: uivraeus/hbase_docker:2.5.7
    restart: unless-stopped
    command:
      - "/bin/bash"
      - "-c"
      - "start-hbase.sh; tail -f /root/hbase-bin/logs/*.log"
    volumes:
      - hbase-data:/root/tmp
      - ../lab:/workspace/lab:ro

volumes:
  postgres-data:
  hbase-data:
